python3 cann't cyclic -l 0x61616162
cyclic -l 0x61616162
Traceback (most recent call last):
  File "/usr/local/bin/cyclic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/commandline/common.py", line 32, in main
    pwnlib.commandline.main.main()
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/commandline/main.py", line 54, in main
    commands[args.command](args)
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/commandline/cyclic.py", line 75, in main
    if not all(c in alphabet for c in pat):
  File "/usr/local/lib/python3.5/dist-packages/pwnlib/commandline/cyclic.py", line 75, in <genexpr>
    if not all(c in alphabet for c in pat):
TypeError: 'in <string>' requires string as left operand, not int